import centroids from "./zip-centroids.json";
import { normalizeZip, isValidZip } from "./zones";

/**
 * ZIP-code distance, for radius-based delivery areas.
 *
 * A yard says "we deliver within 30 miles" instead of listing every ZIP. To answer whether a
 * given delivery ZIP is inside that circle we need each ZIP's location, so we ship a bundled
 * table of US ZIP centroids (lib/zip-centroids.json, ~42k rows, regenerated by
 * scripts/gen-zip-centroids.mjs). It's imported server-side only — matchZone runs on the quote
 * and order paths, never in the browser — so the megabyte of data never reaches a customer.
 *
 * Distance is measured centroid-to-centroid, which is the same granularity the storefront asks
 * for (a customer enters a ZIP, not a street address). It's approximate at the edge of a circle
 * by a mile or two, which is the right precision for "do we come out this far".
 */

// The JSON is one entry per ZIP: "43004": [lat, lng]. TypeScript infers the values as number[]
// from the data file, so we assert the tuple shape through unknown (the file is generated, and
// gen-zip-centroids.mjs guarantees exactly two numbers per row).
const TABLE = centroids as unknown as Record<string, [number, number]>;

export type LatLng = { lat: number; lng: number };

/** Centroid of a US ZIP, or null if we don't have it (rare PO-box-only ZIPs, or non-US). */
export function zipCoords(zip: string): LatLng | null {
  const z = normalizeZip(zip);
  if (!isValidZip(z)) return null;
  const hit = TABLE[z];
  return hit ? { lat: hit[0], lng: hit[1] } : null;
}

const EARTH_RADIUS_MILES = 3958.8;
const toRad = (deg: number) => (deg * Math.PI) / 180;

/** Great-circle distance between two coordinates, in miles. */
export function haversineMiles(a: LatLng, b: LatLng): number {
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 + Math.sin(dLng / 2) ** 2 * Math.cos(lat1) * Math.cos(lat2);
  return 2 * EARTH_RADIUS_MILES * Math.asin(Math.min(1, Math.sqrt(h)));
}

/**
 * Miles between two US ZIPs, or null if either ZIP isn't in the table. Callers treat null as
 * "can't determine" rather than "out of range", so an unknown ZIP never silently blocks an order.
 */
export function zipDistanceMiles(zipA: string, zipB: string): number | null {
  const a = zipCoords(zipA);
  const b = zipCoords(zipB);
  if (!a || !b) return null;
  return haversineMiles(a, b);
}
